CBA-155: Update distribution task definition

diff --git a/.github/workflows/ci-develop.yml b/.github/workflows/ci-develop.yml
--- a/.github/workflows/ci-develop.yml
+++ b/.github/workflows/ci-develop.yml
@@ -2,11 +2,11 @@ name: ci-develop
 on:
   push:
     branches:
-    - development
-    - feature/CBA-155-cicd
+      - development
+      - feature/CBA-155-cicd
   pull_request:
     types:
-    - closed
+      - closed
 
 jobs:
   build-submission:
@@ -49,9 +49,6 @@ jobs:
           while( ! wget -T 10 -q -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
           ./clair-scanner -c http://localhost:6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA} || true
           cat gl-container-scanning-report.json
-      - name: Install AWS CLI
-        run: |
-          sudo apt-get install --yes awscli
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -69,9 +66,6 @@ jobs:
     needs:
       - build-submission
     steps:
-      - name: Install AWS CLI
-        run: |
-          sudo apt-get install --yes awscli
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -109,9 +103,6 @@ jobs:
     needs:
       - build-submission
     steps:
-      - name: Install AWS CLI
-        run: |
-          sudo apt-get install --yes awscli
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -151,3 +142,187 @@ jobs:
           service: ${{ steps.set-service-output.outputs.service }}
           cluster: ${{ secrets.CLUSTER_NAME_DEV }}
           wait-for-service-stability: false
+
+#  deploy-tst-submission-int:
+#    runs-on: ubuntu-latest
+#    needs:
+#      - build-submission
+#    steps:
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TST_PUSHECR }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TST_PUSHECR }}
+#          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+#      - name: Retrieve Task Definition for external service on TST
+#        run: |
+#          aws ecs describe-task-definition --task-definition "${{ secrets.ECS_TASK_FAMILY_SUBMISSION_TST }}-int" --query taskDefinition > task-definition.json
+#      - name: Set image name as output
+#        id: set-image-output
+#        run: |
+#          echo "::set-output name=image::${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA}"
+#      - name: Update Task Definition for TST with new image
+#        id: render-task-def
+#        uses: aws-actions/amazon-ecs-render-task-definition@v1
+#        with:
+#          task-definition: task-definition.json
+#          container-name: "${{ secrets.ECS_CONTAINER_NAME_SUBMISSION_TST }}-int"
+#          image: "${{ steps.set-image-output.outputs.image }}"
+#      - name: Get service to update
+#        id: set-service-output
+#        run: |
+#          echo "::set-output name=service::$(aws ecs list-services --cluster ${{ secrets.CLUSTER_NAME_TST }} --output text | grep SubmissionInt | awk -F'/' '{print $2}')"
+#      - name: Deploy services with new task definition
+#        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
+#        with:
+#          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
+#          service: ${{ steps.set-service-output.outputs.service }}
+#          cluster: ${{ secrets.CLUSTER_NAME_TST }}
+#          wait-for-service-stability: false
+#
+#  deploy-tst-submission:
+#    runs-on: ubuntu-latest
+#    needs:
+#      - build-submission
+#    steps:
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TST_PUSHECR }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TST_PUSHECR }}
+#          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+#      - name: Retrieve Task Definition for external service on TST
+#        run: |
+#          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_FAMILY_SUBMISSION_TST }} --query taskDefinition > task-definition.json
+#      - name: Show task definition
+#        run: |
+#          cat task-definition.json
+#      - name: Set image name as output
+#        id: set-image-output
+#        run: |
+#          echo "::set-output name=image::${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA}"
+#      - name: Update Task Definition for TST with new image
+#        id: render-task-def
+#        uses: aws-actions/amazon-ecs-render-task-definition@v1
+#        with:
+#          task-definition: task-definition.json
+#          container-name: "${{ secrets.ECS_CONTAINER_NAME_SUBMISSION_TST }}"
+#          image: "${{ steps.set-image-output.outputs.image }}"
+#        env:
+#          IMAGE: "${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA}"
+#      - name: Show updated task definition
+#        run: |
+#          cat ${{ steps.render-task-def.outputs.task-definition }}
+#      - name: Get service to update
+#        id: set-service-output
+#        run: |
+#          echo "::set-output name=service::$(aws ecs list-services --cluster ${{ secrets.CLUSTER_NAME_TST }} --output text | grep SubmissionInt | grep -v Int | awk -F'/' '{print $2}')"
+#      - name: Deploy services with new task definition
+#        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
+#        with:
+#          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
+#          service: ${{ steps.set-service-output.outputs.service }}
+#          cluster: ${{ secrets.CLUSTER_NAME_TST }}
+#          wait-for-service-stability: false
+
+  build-distribution:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - uses: actions/cache@v1
+        env:
+          cache-name: m2
+        with:
+          path: ~/.m2/repository
+          key: ${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
+          restore-keys: ${{ env.cache-name }}-
+      - name: Lint Dockerfile
+        run: |
+          docker pull hadolint/hadolint
+          docker run --rm --interactive hadolint/hadolint < ./services/distribution/Dockerfile
+      - name: docker build
+        run: |
+          docker build --pull --rm \
+          -f services/distribution/Dockerfile \
+          --tag ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}:${GITHUB_SHA} \
+          .
+      - name: Run a vulnerability scan on the docker image
+        run: |
+          docker pull arminc/clair-db:latest
+          docker run -d --name db arminc/clair-db:latest
+          docker run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:v2.0.1
+          sudo apt-get update
+          sudo apt-get install -y wget ca-certificates nc || true
+          wget https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64
+          mv clair-scanner_linux_amd64 clair-scanner
+          chmod +x clair-scanner
+          touch clair-whitelist.yml
+          while( ! wget -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1; docker ps; docker logs clair; docker logs db; nc -v localhost 6060; done
+          retries=0
+          echo "Waiting for clair daemon to start"
+          while( ! wget -T 10 -q -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
+          ./clair-scanner -c http://localhost:6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}:${GITHUB_SHA} || true
+          cat gl-container-scanning-report.json
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TOOLING_PUSHECR }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TOOLING_PUSHECR }}
+          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+      - name: docker push ecr
+        run: |
+          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_HOST }}
+          docker push ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBTION }}:${GITHUB_SHA}
+
+  deploy-dev-distribution:
+    runs-on: ubuntu-latest
+    needs:
+      - build-distribution
+    steps:
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV_PUSHECR }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV_PUSHECR }}
+          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+      - name: Retrieve Task Definition for external service on DEV
+        run: |
+          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_FAMILY_DISTRIBUTION_DEV }} --query taskDefinition > task-definition.json
+      - name: Show task definition
+        run: |
+          cat task-definition.json
+      - name: Set image name as output
+        id: set-image-output
+        run: |
+          echo "::set-output name=image::${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}:${GITHUB_SHA}"
+      - name: Update Task Definition for DEV with new image
+        id: render-task-def
+        uses: aws-actions/amazon-ecs-render-task-definition@v1
+        with:
+          task-definition: task-definition.json
+          container-name: "${{ secrets.ECS_CONTAINER_NAME_DISTRIBUTION_DEV }}"
+          image: "${{ steps.set-image-output.outputs.image }}"
+        env:
+          IMAGE: "${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}:${GITHUB_SHA}"
+      - name: Show updated task definition
+        run: |
+          cat ${{ steps.render-task-def.outputs.task-definition }}
+      - name: Deploy new task definition
+        id: deploy-task-definition
+        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
+        with:
+          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
+          wait-for-service-stability: false
+      - name: Determine scheduled task name
+        id: get-scheduled-task-name
+        run: |
+          echo "::set-output name=scheduledtaskname:$(aws events list-rules --query "Rules[*]|[?contains(Name,'Distr')].Name" --output text)"
+      - name: Create new target config for the distribution scheduled task
+        id: update-scheduled-task-distribution
+        run: |
+          aws events list-targets-by-rule --rule "${{ steps.get-scheduled-task-name.outputs.scheduledtaskname }}" | \
+            jq '.Targets[0].EcsParameters.TaskDefinitionArn = "${{ steps.deploy-task-definition.outputs.task-definition-arn }}"' > targetdef.json
+          aws events put-targets --cli-input-json file://./targetdef.json --rule "${{ steps.get-scheduled-task-name.outputs.scheduledtaskname }}"
+
