CBA-155: Add ci-develop-pr workflow

diff --git a/.github/workflows/ci-develop.yml b/.github/workflows/ci-develop.yml
--- a/.github/workflows/ci-develop.yml
+++ b/.github/workflows/ci-develop.yml
@@ -32,6 +32,31 @@ jobs:
       env:
         ECR_REPO_HOST: ${{ secrets.ECR_REPO_HOST }}
         ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}
+    - name: clair the image
+      run: |
+        docker pull arminc/clair-db:latest
+        docker run -d --name db arminc/clair-db:latest
+        docker run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:v2.0.1
+        sudo apt-get update
+        sudo apt-get install -y wget ca-certificates nc || true
+        wget https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64
+        mv clair-scanner_linux_amd64 clair-scanner
+        chmod +x clair-scanner
+        touch clair-whitelist.yml
+        while( ! wget -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1; docker ps; docker logs clair; docker logs db; nc -v localhost 6060; done
+        retries=0
+        echo "Waiting for clair daemon to start"
+        while( ! wget -T 10 -q -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
+        ./clair-scanner -c http://localhost:6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml  myalpine:latest|| true
+        cat gl-container-scanning-report.json
+    - uses: actions/upload-artifact@v1
+      with:
+        name: clair-result
+        path: gl-container-scanning-report.json
+    - uses: actions/upload-artifact@v1
+      with:
+        name: clair-log
+        path: clair.log
     - name: docker push ecr
       run: |
         sudo apt-get install --yes awscli
