CBA-155: CICD rewrite for dev environment (for now)

diff --git a/.github/workflows/ci-develop.yml b/.github/workflows/ci-develop.yml
--- a/.github/workflows/ci-develop.yml
+++ b/.github/workflows/ci-develop.yml
@@ -3,118 +3,139 @@ on:
   push:
     branches:
     - development
-env:
-  AWS_DEFAULT_REGION: eu-central-1
-jobs:
-  build-distribution:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-    - uses: actions/cache@v1
-      env:
-        cache-name: m2
-      with:
-        path: ~/.m2/repository
-        key: ${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
-        restore-keys: ${{ env.cache-name }}-
-    - uses: actions/setup-java@v1
-      with:
-        java-version: 11
-    - name: docker build
-      run: |
-        docker build --pull --rm \
-        -f services/distribution/Dockerfile \
-        --tag ${ECR_REPO_HOST}/${ECR_REPO_NAME}:develop \
-        --tag ${ECR_REPO_HOST}/${ECR_REPO_NAME}:latest \
-        .
-      env:
-        ECR_REPO_HOST: ${{ secrets.ECR_REPO_HOST }}
-        ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}
-    - name: clair the image
-      run: |
-        docker pull arminc/clair-db:latest
-        docker run -d --name db arminc/clair-db:latest
-        docker run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:v2.0.1
-        sudo apt-get update
-        sudo apt-get install -y wget ca-certificates nc || true
-        wget https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64
-        mv clair-scanner_linux_amd64 clair-scanner
-        chmod +x clair-scanner
-        touch clair-whitelist.yml
-        while( ! wget -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1; docker ps; docker logs clair; docker logs db; nc -v localhost 6060; done
-        retries=0
-        echo "Waiting for clair daemon to start"
-        while( ! wget -T 10 -q -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
-        ./clair-scanner -c http://localhost:6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml  myalpine:latest|| true
-        cat gl-container-scanning-report.json
-    - uses: actions/upload-artifact@v1
-      with:
-        name: clair-result
-        path: gl-container-scanning-report.json
-    - uses: actions/upload-artifact@v1
-      with:
-        name: clair-log
-        path: clair.log
-    - name: docker push ecr
-      run: |
-        sudo apt-get install --yes awscli
-        aws ecr get-login-password | docker login --username AWS --password-stdin ${ECR_REPO_HOST}
-        docker push ${ECR_REPO_HOST}/${ECR_REPO_NAME}:develop
-        docker push ${ECR_REPO_HOST}/${ECR_REPO_NAME}:latest
-      env:
-        ECR_REPO_HOST: ${{ secrets.ECR_REPO_HOST }}
-        ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME_DISTRIBUTION }}
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PUSHECR }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PUSHECR }}
+    - feature/CBA-155-cicd
+  pull_request:
+    types:
+    - closed
 
+jobs:
   build-submission:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-    - uses: actions/cache@v1
-      env:
-        cache-name: m2
-      with:
-        path: ~/.m2/repository
-        key: ${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
-        restore-keys: ${{ env.cache-name }}-
-    - uses: actions/setup-java@v1
-      with:
-        java-version: 11
-    - name: docker build
-      run: |
-        docker build --pull --rm \
-        -f services/submission/Dockerfile \
-        --tag ${ECR_REPO_HOST}/${ECR_REPO_NAME}:develop \
-        --tag ${ECR_REPO_HOST}/${ECR_REPO_NAME}:latest \
-        .
-      env:
-        ECR_REPO_HOST: ${{ secrets.ECR_REPO_HOST }}
-        ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME_SUBMISSION }}
-    - name: docker push ecr
-      run: |
-        sudo apt-get install --yes awscli
-        aws ecr get-login-password | docker login --username AWS --password-stdin ${ECR_REPO_HOST}
-        docker push ${ECR_REPO_HOST}/${ECR_REPO_NAME}:develop
-        docker push ${ECR_REPO_HOST}/${ECR_REPO_NAME}:latest
-      env:
-        ECR_REPO_HOST: ${{ secrets.ECR_REPO_HOST }}
-        ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME_SUBMISSION }}
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PUSHECR }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PUSHECR }}
-    - name: Force deploy service on ECS in tst
-      run: |
-        sudo apt-get install --yes awscli
-        for service in ${SERVICE_NAMES}; do
-          aws ecs update-service --cluster ${CLUSTER_NAME} --force-new-deployment --service ${service} --region ${AWS_REGION:-eu-central-1}
-        done
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        SERVICE_NAMES: ${{ secrets.SERVICE_NAMES_SUBMISSION }}
-        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - uses: actions/cache@v1
+        env:
+          cache-name: m2
+        with:
+          path: ~/.m2/repository
+          key: ${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
+          restore-keys: ${{ env.cache-name }}-
+      - name: Lint Dockerfile
+        run: |
+          docker pull hadolint/hadolint
+          docker run --rm --interactive hadolint/hadolint < ./Dockerfile
+      - name: docker build
+        run: |
+          docker build --pull --rm \
+          -f services/distribution/Dockerfile \
+          --tag ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA} \
+          .
+      - name: Run a vulnerability scan on the docker image
+        run: |
+          docker pull arminc/clair-db:latest
+          docker run -d --name db arminc/clair-db:latest
+          docker run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:v2.0.1
+          sudo apt-get update
+          sudo apt-get install -y wget ca-certificates nc || true
+          wget https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64
+          mv clair-scanner_linux_amd64 clair-scanner
+          chmod +x clair-scanner
+          touch clair-whitelist.yml
+          while( ! wget -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1; docker ps; docker logs clair; docker logs db; nc -v localhost 6060; done
+          retries=0
+          echo "Waiting for clair daemon to start"
+          while( ! wget -T 10 -q -O /dev/null http://localhost:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
+          ./clair-scanner -c http://localhost:6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA} || true
+          cat gl-container-scanning-report.json
+      - name: Install AWS CLI
+        run: |
+          sudo apt-get install --yes awscli
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TOOLING_PUSHECR }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TOOLING_PUSHECR }}
+          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+      - name: docker push ecr
+        run: |
+          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_HOST }}
+          docker push ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME_SUBMISSION }}:${GITHUB_SHA}
 
+
+  deploy-dev-submission-int:
+    runs-on: ubuntu-latest
+    needs:
+      - build-submission
+    steps:
+      - name: Install AWS CLI
+        run: |
+          sudo apt-get install --yes awscli
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV_PUSHECR }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV_PUSHECR }}
+          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+      - name: Retrieve Task Definition for external service on DEV
+        run: |
+          aws ecs describe-task-definition --task-definition "${{ secrets.ECS_TASK_FAMILY_DEV }}-int" --query taskDefinition > task-definition.json
+      - name: Show task definition
+        run: |
+          cat task-definition.json
+      - name: Update Task Definition for DEV with new image
+        id: render-task-def-dev
+        uses: aws-actions/amazon-ecs-render-task-definition@v1
+        with:
+          task-definition: task-definition.json
+          container-name: "${{ secrets.ECS_CONTAINER_NAME_DEV }}-int"
+          image: "${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME }}:${{ env.GITHUB_SHA }}"
+      - name: Get service to update
+        run: |
+          echo "::set-env name=SERVICE::$(aws ecs list-services --cluster ${{ secrets.CLUSTER_NAME_DEV }} --output text| grep SubmissionInt | awk -F'/' '{print $2}')"
+      - name: Deploy services with new task definition
+        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
+        with:
+          task-definition: ${{ steps.render-task-def-dev.outputs.task-definition }}
+          service: ${{ env.SERVICE }}
+          cluster: ${{ secrets.CLUSTER_NAME_DEV }}
+          wait-for-service-stability: false
+
+  deploy-dev-submission:
+    runs-on: ubuntu-latest
+    needs:
+      - build-submission
+    steps:
+      - name: Install AWS CLI
+        run: |
+          sudo apt-get install --yes awscli
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV_PUSHECR }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV_PUSHECR }}
+          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+      - name: Retrieve Task Definition for external service on DEV
+        run: |
+          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_FAMILY_DEV }} --query taskDefinition > task-definition.json
+      - name: Show task definition
+        run: |
+          cat task-definition.json
+      - name: Update Task Definition for DEV with new image
+        id: render-task-def-dev
+        uses: aws-actions/amazon-ecs-render-task-definition@v1
+        with:
+          task-definition: task-definition.json
+          container-name: "${{ secrets.ECS_CONTAINER_NAME_DEV }}"
+          image: "${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME }}:${{ env.GITHUB_SHA }}"
+      - name: Get service to update
+        run: |
+          echo "::set-env name=SERVICE::$(aws ecs list-services --cluster ${{ secrets.CLUSTER_NAME_DEV }} --output text| grep Submission | grep -v Int | awk -F'/' '{print $2}')"
+      - name: Deploy services with new task definition
+        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
+        with:
+          task-definition: ${{ steps.render-task-def-dev.outputs.task-definition }}
+          service: ${{ env.SERVICE }}
+          cluster: ${{ secrets.CLUSTER_NAME_DEV }}
+          wait-for-service-stability: false
